language: csharp
mono: none
sudo: required
dist: bionic
dotnet: 3.1

branches:
  only:
    - master
    - develop
    
before_script:
  - chmod -R a+x samples
  - chmod -R a+x scripts
  - chmod -R a+x src
  
script:
  - ./scripts/build.sh
  - ./scripts/pack.sh
  
notifications:
  email:
    on_success: never
    on_failure: always