language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 3.1
install:
  - dotnet restore
branches:
  only:
    - master
    - develop
before_script:
  - chmod -R a+x scripts
  - chmod -R a+x src
script:
  - dotnet build -c release
  - dotnet test tests/FeatuR.Tests/FeatuR.Tests.csproj
  - ./scripts/pack.sh
notifications:
  email:
    on_success: never
    on_failure: always