language: csharp
mono: none
sudo: required
dist: bionic
dotnet: 3.1
addons:
  sonarcloud:
    organization: raulcanales
    token:
      secure: $SONAR_TOKEN
branches:
  only:
  - master
  - dev
  
install:
- dotnet tool install --global dotnet-sonarscanner
  
before_script:
- chmod -R a+x scripts
- chmod -R a+x src
script:
- dotnet sonarscanner begin /k:"FeatuR" /d:sonar.login="$SONAR_TOKEN" /d:sonar.exclusions="**/bin/**/*,**/obj/**/*" /d:sonar.cs.opencover.reportPaths="lcov.opencover.xml" || true
- dotnet test ./test/FeatuR.Tests/FeatuR.Tests.csproj -c Release
- dotnet build -c Release
-dotnet sonarscanner end /d:sonar.login="$SONAR_TOKEN" || true
- ./scripts/pack.sh
notifications:
  email:
    on_success: never
    on_failure: never
