language: csharp
mono: none
sudo: required
dist: bionic
dotnet: 3.1
solution: FeatuR.sln
addons:
  sonarcloud:
    organization: raulcanales
    
branches:
  only:
  - master
  - dev

before_install:
- bash ./scripts/travis-ci-install-dependencies.sh

before_script:
- chmod -R a+x scripts
- chmod -R a+x src

script:
- git fetch --unshallow || true
- bash ./scripts/travis-ci-build.sh

notifications:
  email:
    on_success: never
    on_failure: never
