name: NuGet Package Deploy
on:
  push:
    tags:
    - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install dotnet tool
        run: dotnet tool install -g dotnetCampus.TagToVersion
      - name: Set tag to version
        run: dotnet TagToVersion -t ${{ github.ref }}
