name: CI
on:
  push:
    branches:
      - master
jobs:
  codacy-coverage-reporter:
    name: Codacy report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Tests
        run: dotnet test ./test/FeatuR.Tests/FeatuR.Tests.csproj -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
      - name: Run codacy-coverage-reporter
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: test/**/coverage.opencover.xml
  sonarcloud:
    name: SonarCloud report
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Sonarscanner for dotnet
        uses: raulcanales/dotnet-sonarscanner@v2.2
        with:
          buildCommand: dotnet build ./FeatuR.sln -c Release
          testCommand: dotnet test ./FeatuR.sln --no-build -c Release -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
          projectKey: raulcanales_FeatuR
          projectName: FeatuR
          sonarOrganisation: raulcanales
          beginArguments: >
              /d:sonar.verbose="false"
              /d:sonar.exclusions="**/bin/**/*,**/obj/**/*"
              /d:sonar.cs.opencover.reportsPaths="test/**/coverage.opencover.xml"
              /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
            MYSQL_ROOT_PASSWORD: "test123456"
        ports:
            - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'
      - name: Build with dotnet
        run: dotnet build --configuration Release
      - name: Test with dotnet
        env:
          ConnectionStringMySQL: "Server=localhost; Port=${{ job.services.mysql.ports[3306] }}; User=root; Password=test123456; Database=featur;"
        run: dotnet test
  deploy:
    name: Deploy to MyGet
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pack NuGet package
        run: dotnet pack --configuration Release --version-suffix "ci"
      - name: Push package to MyGet
        run: dotnet nuget push **/*.nupkg
              --api-key ${{ secrets.MYGET_DEPLOY_KEY }}
              --source https://www.myget.org/F/featur/api/v3/index.json
              --no-symbols
              --skip-duplicate
